version: "3.7"

services:
  app_python:
    image: el3os/moscow_time_python:latest
    container_name: app_python
    restart: always
    user: root
    ports:
      - "5000:5000"
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - wget --no-verbose --tries=1 -O /dev/null http://localhost:5000/healthcheck || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
    volumes:
      - app_python_visits:/app/volume/



volumes:
  app_python_visits:
